"""Abstract storage backend — implemented by PostgresStore (cloud) and JSONFileStore (local, TBD)."""

from abc import ABC, abstractmethod


class StorageBackend(ABC):
    """Pluggable storage. One implementation: PostgresStore. JSONFileStore TBD."""

    @abstractmethod
    def initialize(self): ...
    @abstractmethod
    def health_check(self) -> bool: ...
    @abstractmethod
    def get_rules(self, domain=None, min_confidence=1) -> list[dict]: ...
    @abstractmethod
    def get_rule(self, rule_id: str) -> dict | None: ...
    @abstractmethod
    def add_rule(self, rule: dict) -> dict: ...
    @abstractmethod
    def delete_rule(self, rule_id: str) -> bool: ...
    @abstractmethod
    def promote_rule(self, rule_id: str) -> dict | None: ...
    @abstractmethod
    def demote_rule(self, rule_id: str) -> dict | None: ...
    @abstractmethod
    def search_rules(self, query: str, domain=None, min_confidence=1, limit=None, rule_type=None) -> list[dict]: ...
    @abstractmethod
    def get_domain_stats(self, domain=None) -> dict: ...
    @abstractmethod
    def get_all_domain_stats(self) -> dict: ...
    @abstractmethod
    def append_timeline(self, entry: dict) -> dict: ...
    @abstractmethod
    def query_timeline(self, **filters) -> list[dict]: ...
    @abstractmethod
    def get_timeline_summary(self, period: str = "weekly") -> dict: ...
    @abstractmethod
    def set_retention(self, rule_id: str, policy: str, set_by: str = "", reason: str = "") -> dict: ...
    @abstractmethod
    def get_retention(self, rule_id: str) -> str: ...
    @abstractmethod
    def get_permanent_rules(self) -> list[str]: ...
    @abstractmethod
    def archive_rule(self, rule_id: str, reason: str = "", archived_by: str = "") -> dict | None: ...
    @abstractmethod
    def get_archived_rules(self) -> list[dict]: ...
    @abstractmethod
    def restore_rule(self, rule_id: str) -> bool: ...
    @abstractmethod
    def set_permission(self, rule_id: str, clearance: str, allowed_roles=None, allowed_teams=None) -> dict: ...
    @abstractmethod
    def get_permission(self, rule_id: str) -> dict | None: ...
    @abstractmethod
    def add_org_rule(self, rule: dict) -> dict: ...
    @abstractmethod
    def get_org_rules(self, min_confidence=1, project=None, tags=None, scope=None) -> list[dict]: ...
    @abstractmethod
    def search_org(self, query: str, project=None, tags=None, role=None, limit=None, min_confidence=1) -> list[dict]: ...
    @abstractmethod
    def get_cross_project_context(self, project: str, query: str, limit: int = 10) -> list[dict]: ...
    @abstractmethod
    def get_org_stats(self) -> dict: ...
    @abstractmethod
    def write_observation(self, session_id: str, observation: dict) -> None: ...
    @abstractmethod
    def get_observations(self, session_id: str, domain=None) -> list[dict]: ...
    @abstractmethod
    def count_observations(self, session_id: str) -> int: ...
    @abstractmethod
    def clear_observations(self, session_id: str, domain=None) -> None: ...
    @abstractmethod
    def write_blob(self, namespace: str, key: str, data: dict) -> None: ...
    @abstractmethod
    def read_blob(self, namespace: str, key: str) -> dict | None: ...
    @abstractmethod
    def list_blobs(self, namespace: str) -> list[str]: ...
    @abstractmethod
    def delete_blob(self, namespace: str, key: str) -> bool: ...
